<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net6.0-windows</TargetFramework>
    <RootNamespace>FFmpeg GUI</RootNamespace>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <Version>0.3.0</Version>
    <Authors>GuiguiBlocCraft</Authors>
    <ApplicationIcon>ffmpeg_gui.ico</ApplicationIcon>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="xFFmpeg.NET" Version="7.2.0"/>
    <PackageReference Include="WindowsAPICodePack" Version="8.0.6"/>
    <Content Include="ffmpeg_gui.ico"/>
  </ItemGroup>
</Project>